# Generated by Django 5.1.2 on 2024-11-05 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegisteredTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must contain only letters and spaces.', regex='^[a-zA-Z\\s]+$')])),
                ('loginid', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Login ID must be alphanumeric and between 5-20 characters.', regex='^[a-zA-Z0-9]{5,20}$')])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('mobile', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10 digits.', regex='^\\d{10}$')])),
                ('password', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Password must contain at least 8 characters, including letters and numbers.', regex='^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d@,$,%,&]{8,}$')])),
                ('locality', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Locality must contain only letters, numbers, and spaces.', regex='^[\\w\\s]+$')])),
                ('state', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='State must contain only letters, numbers, and spaces.', regex='^[\\w\\s]+$')])),
                ('status', models.CharField(default='Waiting', max_length=10)),
            ],
        ),
    ]
